---
- name: Install required packages (Debian)
  hosts: all
  become: yes
  tasks:
    - name: Update package list
      ansible.builtin.apt:
        update_cache: yes

    - name: Install curl
      ansible.builtin.apt:
        name: curl
        state: present

- name: Install K3s on Master
  hosts: cicdorchestrator
  become: yes
  tasks:
    - name: Download and install K3s
      ansible.builtin.shell: curl -sfL https://get.k3s.io | sh -

    - name: Get Node Token
      ansible.builtin.shell: cat /var/lib/rancher/k3s/server/node-token
      register: node_token

- name: Install K3s on Worker
  hosts: monitoringhub
  become: yes
  tasks:
    - name: Download and install K3s with Master token
      ansible.builtin.shell: >
        curl -sfL https://get.k3s.io | K3S_URL=https://{{ hostvars['cicdorchestrator']['ansible_host'] }}:6443 K3S_TOKEN={{ hostvars['cicdorchestrator']['node_token'].stdout }} sh -
